owner: periodo
repo: periodo-status

sites:
  - name: PeriodO data
    url: https://data.perio.do
  - name: PeriodO client
    url: https://client.perio.do
  - name: PeriodO TTL
    url: https://n2t.net/ark:/99152/p0dataset.ttl
  - name: PeriodO CSV
    url: https://n2t.net/ark:/99152/p0dataset.csv
  - name: PeriodO places graph
    url: https://data.perio.do/graphs/places
  - name: PeriodO legacy subdomain
    url: https://test.perio.do

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /periodo-status
  logoUrl: https://raw.githubusercontent.com/periodo/periodo-website/source/images/sundial.svg
  name: PeriodO status
  introTitle: "Current and past status of PeriodO HTTP services."
  introMessage: This page tracks the status of various HTTP services maintained by the [PeriodO](https://github.com/periodo) project.
  navbar:
    - title: Status
      href: /
    - title: PeriodO
      href: https://github.com/$OWNER

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
